spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cinema
    username: cinema
    password: cinema
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
