server:
  port: 8084
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: cinema
    password: cinema
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: health,info
