server:
  port: 8084
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://postgres:5432/cinema
    username: cinema
    password: cinema
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: health,info
